{
 "title": "Logs / App",
 "description": "Log Viewer Dashboard for Loki",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "App", "query": "label_values(job)" },
   { "name": "search", "label": "String Match" }
  ]
 },
 "panels": [
  {
   "title": "Type log pie chart",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"systemd-journal\"} | detected_level = \"debug\" [$__auto])) by (detected_level)",
     "legendFormat": "{{detected_level}}"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"systemd-journal\"} | detected_level = \"info\" [$__auto])) by (detected_level)",
     "legendFormat": "{{detected_level}}"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"systemd-journal\"} | detected_level = \"unknown\" [$__auto])) by (detected_level)",
     "legendFormat": "{{detected_level}}"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"systemd-journal\"} | detected_level = \"warn\" [$__auto])) by (detected_level)",
     "legendFormat": "{{detected_level}}"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"systemd-journal\"} | detected_level = \"error\" [$__auto])) by (detected_level)",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Metric query",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"systemd-journal\"} [$__auto])) by (detected_level)",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Warn/Error's logs",
   "type": "logs",
   "description": "All warn/error's logs will be printed here",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$app\"} | logfmt | detected_level =~ `err|error|emerg|emergency|fatal|crit|critical|warn` | line_format \"Service: {{ if .logger }}{{ .logger }}{{ else }}Loki{{ end }} | Message: {{ if .msg }}{{ .msg }}{{ else }}No Message{{ end }}\""
    }
   ]
  },
  {
   "title": "Logs Informative",
   "type": "logs",
   "description": "All infos logs will be printed here",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$app\"} | logfmt | detected_level =~ `info|notice|debug|trace` | line_format \"Service: {{ if .logger }}{{ .logger }}{{ else }}Loki{{ end }} | Message: {{ if .msg }}{{ .msg }}{{ else }}No Message{{ end }}\""
    }
   ]
  }
 ]
}